---
title: "Group Document"
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
editor: visual
execute:
  echo: true
  cache: true
  freeze: auto
date: 2025-10-07
authors: 
- Isabella T. Christoffersen (s235342)
- Karolina Nordkamp (s244854)
- Malaika Khiljee (s245618)
- Kasia Muncha (s222846)
- Andreas Bach (s205869)
---

# Aim

ghjk

# Load libraries

```{r}
#| message: false

library("tidyverse")
library(broom) 
library(cowplot)
```

# Load data

The Gravier data has been added to a data folder in the GitHub repository.

```{r}
load("data/gravier.RData")
```

# Data wrangling

```{r}
gravier_clean <- gravier |>
  bind_cols() |>
  as_tibble() |>
  relocate(early_metastasis = y) 

gravier_clean |> 
  slice_sample(n = 10)
```

# Data Analysis

```{r}
pca_fit <- gravier_clean %>% 
  select(where(is.numeric)) %>% # retain only numeric columns
  scale() %>% # scale data
  prcomp() # do PCA

pca_fit_subset <- pca_fit |> 
  tidy() |> 
  head(10)

pca_fit_subset
```

## Figure 1

```{r}
pca_fit %>%
  augment(gravier_clean) %>% # add original dataset back in
  ggplot(aes(.fittedPC1, .fittedPC2, color = early_metastasis)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(poor = "#D55E00", good = "#0072B2")
  ) +
  theme_half_open(12) + background_grid()
```

## Figure 2

dfghj

## Figure 3

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues")
```

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues") |> 
  
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_minimal_hgrid(12)
```

# Conclusion

ghjk
